Description of procRaw
Home > BauerLab > MATLAB > lib > +probe > procRaw.m
procRaw
PURPOSE
procRaw Detrends raw data (temporally and spatially)
SYNOPSIS
function output = procRaw(raw,temporalDetrend,spatialDetrend)
DESCRIPTION
procRaw Detrends raw data (temporally and spatially)
   output = procRaw(raw)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
probeImaging probeImaging Processes tiff file to output hemoglobin data, probe data, and
probeImagingRaw probeImaging Processes tiff file to output hemoglobin data, probe data, and
probeImagingRaw_old probeImaging Processes tiff file to output hemoglobin data, probe data, and
SOURCE CODE
function output = procRaw(raw,temporalDetrend,spatialDetrend)
%procRaw Detrends raw data (temporally and spatially)
%   output = procRaw(raw)
output = raw;
rawSize = size(raw);
tSize = size(raw,4);
% spatial and temporal detrending
rawReshaped = reshape(raw,[],tSize);
if temporalDetrend
    warning('Off');
    timeTrend = zeros(size(rawReshaped));
    for ii = 1:size(rawReshaped,1)
        timeTrend(ii,:) = polyval(polyfit(1:tSize, rawReshaped(ii,:), 4), 1:tSize);
    end
    rawFrameOne = raw(:,:,:,1);
    timeTrend = reshape(timeTrend,rawSize);
    output = bsxfun(@rdivide, output, timeTrend).*repmat(rawFrameOne,1,1,1,tSize);
    warning('On');
end
if spatialDetrend
    % spatial detrending
    spatTrend = bsxfun(@rdivide, mean(raw,4), mean(mean(mean(raw,4))));
    output = bsxfun(@rdivide, output, spatTrend);
end
end